version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo
    command: node --loader ts-node/esm src/index.ts


volumes:
  mongo_data:
